//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rekeningenJSON {
	
	
	public partial class rekeningen {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlTable Table1;
		
		protected System.Web.UI.WebControls.Button ButtonTerug;
		
		protected System.Web.UI.WebControls.Button ButtonJSON;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox1;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox2;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox3;
		
		protected System.Web.UI.WebControls.ListBox kzeJrMndVan;
		
		protected System.Web.UI.WebControls.ListBox kzeJrMndTot;
		
		protected System.Web.UI.WebControls.Label nrrek;
		
		protected System.Web.UI.WebControls.Label txtrek;
		
		protected System.Web.UI.WebControls.GridView GridView1;
		
		protected System.Web.UI.WebControls.Button ButtonWisJrnl;
		
		protected System.Web.UI.WebControls.Button ButtonSaveJrnl;
		
		protected System.Web.UI.WebControls.Button ButtonNieuwJrnl;
		
		protected System.Web.UI.WebControls.Label id;
		
		protected System.Web.UI.WebControls.TextBox jrnref;
		
		protected System.Web.UI.WebControls.ListBox jrmnd;
		
		protected System.Web.UI.WebControls.ListBox van;
		
		protected System.Web.UI.WebControls.ListBox naar;
		
		protected System.Web.UI.WebControls.TextBox bedrag;
		
		protected System.Web.UI.WebControls.ListBox typetransfer;
		
		protected System.Web.UI.WebControls.TextBox beschrijving;
		
		protected System.Web.UI.WebControls.TextBox opmerking;
		
		protected System.Web.UI.WebControls.GridView GridView3;
		
		protected System.Web.UI.WebControls.TextBox feedback;
	}
}
